const prefix = 'data:image/png;base64,'

const white = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+ip1sAAAAASUVORK5CYII='
const green = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mOM3dv8HwAFugKeFHNe2gAAAABJRU5ErkJggg=='
const green2 = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mOsLSv4DwAFPwJkf7xuOwAAAABJRU5ErkJggg=='
const yellow = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/7/wPwAI5ANwEHGVPQAAAABJRU5ErkJggg=='
const yellow2 = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mO8cXX9fwAIRgNdOpasaAAAAABJRU5ErkJggg=='
const orange = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mN80S37HwAGhAKRsld48QAAAABJRU5ErkJggg=='
const red = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mN8rhn2HwAFzAJnxf9sDQAAAABJRU5ErkJggg=='
const blue = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mMMbnrxHwAFqwK+oiXE3gAAAABJRU5ErkJggg=='
const blue2 = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mM03nvtPwAFuALHzaThLAAAAABJRU5ErkJggg=='
const blue3 = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkyuj5DwADYQH3Gb9KdwAAAABJRU5ErkJggg=='
const purple = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mOcmvfiPwAGdwLsInOerQAAAABJRU5ErkJggg=='
const deepPurple = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNMter+DwAEYQIr1DLJIQAAAABJRU5ErkJggg=='
const morePurple = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mOcI9v1HwAE5AJEQOnd/AAAAABJRU5ErkJggg=='
const pink = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP81nPmPwAIHQNPG1c/KwAAAABJRU5ErkJggg=='
const pink2 = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mM85tf3HwAGJwKj3F8CBQAAAABJRU5ErkJggg=='
const gray = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mOsLSv4DwAFPwJkf7xuOwAAAABJRU5ErkJggg=='
const red2 = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNstk38DwAEjgIiTpcmsQAAAABJRU5ErkJggg=='
const green3 = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mM8fP/ufwAIbAOAdKkwIAAAAABJRU5ErkJggg=='
const orange2 = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mM85tf3HwAGJwKj3F8CBQAAAABJRU5ErkJggg=='
const brown = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mOsyAz6DwAEyAI0CG2DPQAAAABJRU5ErkJggg=='

const colors = [
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mO0Scz4DwAD7AIGykeHNgAAAABJRU5ErkJggg==',
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNsfP3lPwAHtgNhjbed3QAAAABJRU5ErkJggg==',
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mO08+/9DwAECAIbYvarOwAAAABJRU5ErkJggg==',
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mPUSjf9DwADUAHH2R4+qQAAAABJRU5ErkJggg==',
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mPsmL/9PwAGdALfLLTZgwAAAABJRU5ErkJggg==',
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mMM2FD3HwAFVQJ/wQSakQAAAABJRU5ErkJggg==',
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mOcUtf+HwAF4QKaLYURggAAAABJRU5ErkJggg==',
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mO007D9DwAC8wGkgAj2wQAAAABJRU5ErkJggg==',
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mPk7Z/6HwAEFAIygk/bbQAAAABJRU5ErkJggg==',
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mM85i3/HwAFQAIxwDfEwwAAAABJRU5ErkJggg==',
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mMU9Hj3HwAEAQJI0J8X3wAAAABJRU5ErkJggg==',
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNUk+f6DwACEgFQ4cywdAAAAABJRU5ErkJggg==',
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mOcd/rmfwAHlANDxXJFGwAAAABJRU5ErkJggg==',
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNsSun9DwAFVwJ0Dslp5gAAAABJRU5ErkJggg==',
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNMMSz/DwAEGgINf5zfKgAAAABJRU5ErkJggg==',
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNcVZn/HwAF+gKTwpRdtAAAAABJRU5ErkJggg==',
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNcVZn/HwAF+gKTwpRdtAAAAABJRU5ErkJggg==',
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mN0z4z6DwAEFAILQQRF+gAAAABJRU5ErkJggg==',
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNMnnr4PwAF2gK8g2AjSgAAAABJRU5ErkJggg==',
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/WT+fwAI3wN/ghaxIAAAAABJRU5ErkJggg==',
  brown, white, green, green2, red2, yellow, blue3, yellow2, orange, orange2, red, green3, pink2, blue, purple, morePurple, blue2, gray, deepPurple, pink].map(color => prefix + color)

const getRandomColor = () => colors[Math.floor(Math.random() * colors.length)]

export default getRandomColor
